### ISSUE TITLE
Tool Seems to Stop on Large Libraries (TV Shows)

### ISSUE THREAD

**Issue by FredG89** [ukdtom/ExportTools.bundle#102] opened 2019-08-12 13:59 UTC
It appears that the tool locks up or just stops exporting information for large tv shows. My export file is about 50MB and stops on the S Alphabet. I'm using v 2.0.0.5 on Plex Server Version 4.0.1. I set the timeout to 10 minutes of 600 seconds.

**Comment by ukdtom** [comment] 2019-08-12 15:49
I need the ExportTools logs in a zip file

**Comment by FredG89** [comment] 2019-08-12 15:55
[ExportTools.zip](https://github.com/ukdtom/ExportTools.bundle/files/3493336/ExportTools.zip)

Here you go.

**Comment by ukdtom** [comment] 2019-08-12 16:02
Logs sadly rolled over, so I don't see the start of the export :(

But looks like you defined an invalid output path!

`2019-08-12 08:49:01,586 (1466935fa700) :  CRITICAL (output:326) - Exception happened in WriteRow-status was [Errno 2] No such file or directory (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/output.py", line 235, in writerow
    os.rename(CurStatusFile, NewStatusFile)
OSError: [Errno 2] No such file or directory`

Remember, that on a synology box, the `plex` user must have full rights to that directory in order to write the file

**Comment by FredG89** [comment] 2019-08-12 16:05
That's the thing. I'm on unraid and I know the file path is valid because it creates the file. It works for movies but at some point through tv shows, it stops. 

![2019-08-12_11-04-57](https://user-images.githubusercontent.com/6701948/62879596-15c6c880-bcf1-11e9-8193-6fd0a53e9503.png)

**Comment by ukdtom** [comment] 2019-08-12 16:13
Sorry, I read it as Synology, and this is indeed strange

What does an ls -la shows on the output directory, and could you try and raise the amount of logs kept, followed by a PMS restart and then reproduce?

Setting `LogNumFiles` should temporary be set to 15
See: https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/

Also, when failed, zip the entire log directory, not only ExportTools logs, so we can see what happens on the PMS side as well

**Comment by ukdtom** [comment] 2019-08-20 19:40
Ping

**Comment by ukdtom** [comment] 2019-08-27 13:45
Closed due to lack of respons

**Comment by FredG89** [comment] 2019-09-14 03:30
Can we reopen? Not quite sure how to do what you're asking.

**Comment by ukdtom** [comment] 2019-09-14 08:03
Reopened, but will close again, if it takes you a month to respond next time!
If you haven't got any idea about changing this, I can only suggest you ask for help in the Plex forums, and tag post with `Synology` since I'm not a Syno dude myself

**Comment by FredG89** [comment] 2019-09-16 19:55
[Logs.zip](https://github.com/ukdtom/ExportTools.bundle/files/3617970/Logs.zip)

Here's all logs.

**Comment by ukdtom** [comment] 2019-09-16 20:21
Logs still roll over, so did you set it to 15?
And note, that you need to restart the PMS after doing so!

When said, I see you have `FindMissing`plugin installed, so please remove, since now embedded into `WebTools`, that you also have installed, and is a lot faster as well as better! (FindMedia Module)

**Comment by FredG89** [comment] 2019-09-17 13:11
I've made the requested changes and uploaded the logs. After removing the FindMissing plugin, it did take longer to fail. 
[Logs.zip](https://github.com/ukdtom/ExportTools.bundle/files/3621416/Logs.zip)

**Comment by ukdtom** [comment] 2019-09-17 13:33
There's absolutely no errors what so ever....

Please browse to http://127.0.0.1:32400/library/metadata/137117&X-Plex-Token=MYTOKEN and grap the xml into a text file, since that's where it stopped

In above, replace MYTOKEN with your real token, that you can find here:
https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

And lastly, please switch off verbose logging, so only debug is enabled!

**Comment by FredG89** [comment] 2019-09-17 14:13
I turned off verbose and am running again.

When I go to the link above (with correct IP and Token), it says "401 Unauthorized".

**Comment by ukdtom** [comment] 2019-09-17 14:22
Then the token is not correct, or you did something wrong with the url.....

Should look something like, and note a fake token here:

`http://127.0.0.1:32400/library/metadata/137117&X-Plex-Token=ytSe64ivCtaj9e5RACo1`

**Comment by FredG89** [comment] 2019-09-17 14:34
It's correct. 

![Capture](https://user-images.githubusercontent.com/6701948/65051235-60f67b80-d92e-11e9-94f9-092236e02cce.PNG)

**Comment by ukdtom** [comment] 2019-09-17 17:19
Ups....My bad here :(

Replace & sign with a questionmark, like:
`http://127.0.0.1:32400/library/metadata/137117?X-Plex-Token=ytSe64ivCtaj9e5RACo1`

**Comment by FredG89** [comment] 2019-09-17 17:35
Here you go.

[XML Data.txt](https://github.com/ukdtom/ExportTools.bundle/files/3622745/XML.Data.txt)

**Comment by ukdtom** [comment] 2019-09-18 12:36
And finally found the reason I guess......

You are simply having too much going on at the same time, so PMS is putting ExportTools to sleep!

Ref:
`Sep 17, 2019 08:09:30.547 [0x14badc7e3700] DEBUG - Putting plug-in com.plexapp.plugins.ExportTools to sleep.
Sep 17, 2019 08:09:30.547 [0x14badc7e3700] DEBUG - Stopping [com.plexapp.plugins.ExportTools].
Sep 17, 2019 08:09:30.547 [0x14badc7e3700] DEBUG - [com.plexapp.plugins.ExportTools] Killing.`

I sadly doesn't know docker, nor debian, but somewhere in your startup files, you should have:
`export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6`

Try and increase that number to like 10, and then restart your PMS
As an alternative, don't scan/refresh your libraries at the same time as ExportTools are running, since doing so involves a lot of agents and scanners, that also is considered plugins by PMS, so I guess you are simply hitting the limit here

**Comment by FredG89** [comment] 2019-09-18 12:54
Thanks, I appreciate it. I've opened a thread over on the Plex forums to find out where this location. Funny thing, I specifically do not update my Plex library while the plugin runs, just in case. Maybe I'm just pushing the limits of what Plex can do.

**Comment by ukdtom** [comment] 2019-09-18 15:10
Well, if so, then this might be what happens:

When a client, in this case ExportTools, request a media, and PMS determines, that the media info is somehow not good enough, it'll refresh by it self

**Comment by ukdtom** [comment] 2019-09-18 15:13
And on debian, try and look in /etc/default/plexmediaserver

**Comment by ukdtom** [comment] 2019-09-18 15:27
And for docker, try and look at:

/root/etc/services.d/plex/run

**Comment by FredG89** [comment] 2019-09-18 16:00
Just changed it. Will let you know what happens.

![Capture](https://user-images.githubusercontent.com/6701948/65164994-8bfecf00-da03-11e9-8b49-cfd4e9c7cbba.PNG)

**Comment by FredG89** [comment] 2019-09-18 17:25
It did get further but I'm not sure if it was because of that number. Apparently, you need to change PlexPluginMode to "Daemon" to prevent it from putting the plugins to sleep. I just gotta figure out where it's located.

**Comment by ukdtom** [comment] 2019-09-18 17:30
Well, doing so, means you take a permanent slot of the 6 avail, and not something I've ever seen anybody need before

Regardless, since I saw you also are running my WebTools plugin, then note that runs in daemon mode

It's all in the info.plist file below the Contents directory, and you can see the syntax in WebTools

https://github.com/ukdtom/WebTools.bundle/blob/553659f81fdca2371e7c58f2c1dc7a0418c63269/Contents/Info.plist#L13

**Comment by ukdtom** [comment] 2019-09-18 17:31
Also note, that when having a lot of plugins in deamon mode, library refresh  will take longer, due to PMS has to unload/load the different agents

**Comment by FredG89** [comment] 2019-09-18 17:36
Refresh is fine, I just need to get a list of my shows so I can clean them up and "archive" them. I'll switch it back after I can get a list.

**Comment by FredG89** [comment] 2019-09-18 18:28
MY GAWD!!! IT WORKEDDD! Adding the PlexPluginMode and setting it to Daemon worked. 

Maybe it's worth adding to a week or something?

**Comment by ukdtom** [comment] 2019-09-18 20:55
Well, as said, first time I came across this, and running a plugin in daemon mode is brutal to PMS, so not something I'll change for ExportTools

Something is causing your PMS to use plugins more or less all the time, and that's what caused this...

You could, and I do suggest you do so, if having enough RAM on your box, raise the `PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS` to 17+, since that's the amount of plugins I count on your box, and remove daemon mode again from ExportTools, just for a small test

And FYI, reason WebTools is running in daemon mode, is to keep it's internal website alive
I also saw you where using trakt, and suspect that's also running in daemon mode, leaving only 4 slots avail in the default settings for the rest

When said, will close this now, and huge thanks for the feedback, since it tought me a lesson in what to look 4 in the future as well ;)


Best Regards, and happy Plexing

Tommy

**Closed as completed by ukdtom** 2019-09-18 20:55 UTC
Labels: Support
